spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dilshan-hesara/d-pay-project-platform-configurations.git
          search-paths: platform,services

server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost